import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

test('Cucumber import, source validation and published dataset execution use a real dedicated agent', async ({ page }) => {
  await page.goto('/auth');
  await page.getByRole('tab', { name: 'Register', exact: true }).click();
  await page.locator('#register-username').fill(`bdd_${randomUUID().replaceAll('-', '')}`);
  await page.locator('#register-password').fill('E2e-Installation!2026');
  await page.locator('#confirm-password').fill('E2e-Installation!2026');
  await page.getByRole('button', { name: 'Create Account', exact: true }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  const created = await page.request.post('/api/agents', { data: { name: 'BDD installation', pool: 'bdd-installation' } });
  expect(created.status()).toBe(201);
  const { token, agent: registered } = await created.json();
  const directory = await mkdtemp(path.join(os.tmpdir(), 'wfm-bdd-ui-'));
  const manifest = path.join(directory, 'profiles.json');
  await writeFile(manifest, JSON.stringify({ profiles: [{ id: 'installation', label: 'Installation support', provider: 'cucumber-js', revision: 'installation-1', maxDurationMs: 30000, projectDirectory: process.cwd(), requirePaths: ['e2e/bdd/support.cjs'], importPaths: [], maxConcurrency: 1, environment: [] }] }));
  const agent = spawn(process.execPath, ['dist/wfm-agent.js'], { env: { ...process.env, WFM_URL: 'http://127.0.0.1:5080', WFM_AGENT_TOKEN: token, WFM_AGENT_MAX_SESSIONS: '1', WFM_BDD_PROFILES: manifest }, stdio: 'ignore' });
  try {
    await expect.poll(async () => (await (await page.request.get('/api/agents')).json()).agents.find((item: { id: string }) => item.id === registered.id)?.connected).toBe(true);
    await page.goto('/settings#agents'); await page.getByRole('button', { name: 'Local agents', exact: true }).click();
    const profiles = page.getByTestId('bdd-profiles');
    await profiles.getByLabel('Profile name', { exact: true }).fill('Installation binding');
    await profiles.getByTestId('bdd-support-target').selectOption('bdd-installation:installation:installation-1');
    await profiles.getByTestId('bdd-profile-save').click();
    await expect(profiles.getByRole('button', { name: 'Edit profile Installation binding', exact: true })).toBeVisible();
    const binding = (await (await page.request.get('/api/bdd/profiles')).json()).profiles[0];
    const feature = '@installation\nFeature: Installed BDD\n  Rule: Selected execution\n    Scenario Outline: Count <n>\n      Given selected count <n>\n      And a document:\n        """\n        payload <n>\n        """\n      Then a table:\n        | <n> |\n      And the selected count is two\n      Examples:\n        | n |\n        | 2 |\n        | 999 |';
    await page.goto('/tests');
    await page.getByRole('button', { name: 'Files', exact: true }).click();
    const files = page.getByTestId('test-files');
    await files.locator('#test-files-file').setInputFiles({ name: 'installed.feature', mimeType: 'text/plain', buffer: Buffer.from(feature) });
    await files.getByTestId('test-files-mode').selectOption('cucumber');
    await files.getByTestId('test-files-profile').selectOption(binding.id);
    await files.getByTestId('test-files-preview').click();
    await expect(files.getByTestId('test-files-gherkin-preview').first()).toContainText('Selected execution');
    await expect(files.getByTestId('test-files-gherkin-preview').first()).toContainText('Doc string');
    await files.getByTestId('test-files-import').click();
    await expect(files).toContainText('Imported.');
    await page.keyboard.press('Escape');
    const all = await (await page.request.get('/api/tests')).json();
    const selected = all.find((item: { bdd?: { exampleLine: number } }) => item.bdd?.exampleLine === 15);
    expect(selected).toBeTruthy();
    await page.getByTestId(`bdd-edit-${selected.id}`).click();
    await page.locator('#bdd-scenario-line').fill('999');
    await page.getByTestId('bdd-save').click();
    await expect(page.getByTestId('bdd-editor-error')).toBeVisible();
    await page.locator('#bdd-scenario-line').fill('4');
    await page.getByTestId('bdd-save').click();
    await expect(page.getByTestId('bdd-editor')).not.toBeVisible();
    const request = (name: string) => ({ id: name, name, method: 'POST', url: 'http://127.0.0.1:5081/echo', queryParams: null, requestHeaders: null, requestBody: null, sourceApiTestId: null });
    expect((await page.request.put(`/api/tests/${selected.id}`, { data: { dataset: [{ label: 'first' }, { label: 'second' }], preconditions: [request('BDD setup')], cleanups: [request('BDD cleanup')] } })).ok()).toBeTruthy();
    expect((await page.request.post(`/api/tests/${selected.id}/publish`, { data: {} })).ok()).toBeTruthy();
    await page.getByTestId(`bdd-edit-${selected.id}`).click();
    await page.getByTestId('bdd-source').fill(feature.replace('| 2 |', '| 7 |'));
    await page.getByTestId('bdd-save').click();
    await expect(page.getByTestId('bdd-editor')).not.toBeVisible();
    const planned = await page.request.post('/api/test-plans', { data: { name: `BDD published ${randomUUID()}`, selectedTests: [{ id: selected.id, type: 'ui' }], browsers: ['chrome', 'firefox'], locales: ['en', 'it'], shards: 2, maxParallelTests: 1 } });
    expect(planned.status()).toBe(201); const plan = await planned.json();
    await page.goto(`/test-plan/${plan.id}/run`);
    const started = page.waitForResponse(response => response.url().endsWith(`/api/run-test-plan/${plan.id}`) && response.request().method() === 'POST');
    await page.getByRole('button', { name: 'Start Execution', exact: true }).click();
    const response = await started; expect(response.ok()).toBeTruthy(); const runId = (await response.json()).data.id;
    await page.getByRole('link', { name: 'View detailed report', exact: true }).click();
    await expect.poll(async () => (await (await page.request.get(`/api/test-plan-executions/${runId}`)).json()).status, { timeout: 60000 }).toBe('completed');
    const run = await (await page.request.get(`/api/test-plan-executions/${runId}`)).json();
    expect(run.results).toHaveLength(2);
    expect(run.results.every((result: { success: boolean }) => result.success)).toBe(true);
    await expect(page.getByTestId('bdd-results').first()).toBeVisible();
    await expect(page.getByTestId('bdd-attachment').first()).toContainText('<script>unsafe()</script>');
    expect(await page.getByTestId('bdd-results').first().locator('script').count()).toBe(0);
    expect(JSON.stringify(run)).not.toContain('fixture-generated-secret');
  } finally {
    agent.kill('SIGTERM');
    await new Promise<void>(resolve => { if (agent.exitCode !== null) resolve(); else { agent.once('exit', () => resolve()); setTimeout(() => { agent.kill('SIGKILL'); resolve(); }, 5000).unref(); } });
    await rm(directory, { recursive: true, force: true });
  }
});
